// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Numerics;

namespace PsychologyHealthCare.Repository.Models;

public partial class ProgramTracking
{
    public int Id { get; set; }

    public string Name { get; set; }

    public long StartTime { get; set; }

    public long EndTime { get; set; }

    public string Rating { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string SystemStatus { get; set; }

    public string Type { get; set; }

    public string Tags { get; set; }
}