// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Numerics;

namespace PsychologyHealthCare.Repository.Models;

public partial class AppointmentTracking
{
    public string Id { get; set; }

    public string Name { get; set; }

    public long StartTime { get; set; }

    public long EndTime { get; set; }

    public string Rating { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string SystemStatus { get; set; }

    public string Holder { get; set; }

    public string Address { get; set; }

    public string Type { get; set; }

    public string ProgramTrackingId { get; set; }

    public virtual ProgramTracking ProgramTracking { get; set; }

    public override string ToString()
    {
        return $"AppointmentTracking: [Id={Id}, Name={Name}, StartTime={StartTime}, EndTime={EndTime}, Rating={Rating}, " +
               $"CreatedDate={CreatedDate}, UpdatedDate={UpdatedDate}, SystemStatus={SystemStatus}, Holder={Holder}, " +
               $"Address={Address}, Type={Type}, ProgramTrackingId={ProgramTrackingId}]";
    }
}